sudo: false

language: generic

services:
  - docker

before_script:
- docker pull mdernst/ubuntu-for-cf-jdk7

# Using travis_wait here seems to cause the job to terminate after 1 minute
# with no error (!).
script:
- REMOTE_ORIGIN_URL=`git config --get remote.origin.url`
- echo "TRAVIS_BRANCH=${TRAVIS_BRANCH}"
- echo "REMOTE_ORIGIN_URL=${REMOTE_ORIGIN_URL}"
- echo "TRAVIS_EVENT_TYPE=${TRAVIS_EVENT_TYPE}"
- echo "TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST}"
- echo "TRAVIS_PULL_REQUEST_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH}"
- echo "TRAVIS_REPO_SLUG=${TRAVIS_REPO_SLUG}"
- >-
  docker run mdernst/ubuntu-for-cf-jdk7 /bin/bash -c "true &&
     export JAVA_HOME=\`which javac|xargs readlink -f|xargs dirname|xargs dirname\` &&
     if [ $TRAVIS_EVENT_TYPE = pull_request ] ; then
       git clone --quiet --depth 9 $REMOTE_ORIGIN_URL sparta
       cd sparta
       git fetch origin +refs/pull/$TRAVIS_PULL_REQUEST/merge
       git checkout -qf FETCH_HEAD
       git config user.email noone@cares.com
       git config user.name Noone Cares
       git remote add theupstream https://github.com/$TRAVIS_REPO_SLUG.git
       git pull --depth 9 theupstream $TRAVIS_BRANCH
     else
       git clone --quiet -b $TRAVIS_BRANCH --depth 9 $REMOTE_ORIGIN_URL sparta
       cd sparta
     fi &&
     java -version &&
     javac -version &&
     ./.travis-build.sh"

git:
  depth: 9
